#!/usr/bin/env bash
# redirection to my github
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

added_location="\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/github.com\/RadouaneBaba;\n\t}"

sudo sed -i "/server_name _;/a $added_location" /etc/nginx/sites-enabled/default

sudo service nginx restart
