#!/usr/bin/env bash
# customize 404
sudo apt-get update
sudo apt-get -y install nginx

# hello world
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

# redirection
added_location="\tlocation /redirect_me {\n\t\t return 301 https:\/\/github.com\/RadouaneBaba;\n\t}"

sudo sed -i "/server_name _;/a $added_location" /etc/nginx/sites-enabled/default

# 404 custom

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null

error_404="\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"

sudo sed -i "/server_name _;/a $error_404" /etc/nginx/sites-enabled/default
# restart server
sudo service nginx restart
