#!/usr/bin/env bash
# shellcheck disable=SC2154
# configure custom HTTP header
sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i "/server_name _;/a\ add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-enabled/default
sudo service nginx start
