#!/usr/bin/env bash
# display to infinity and beyond indefinitely and invincible when trying to shutme down

trap 'echo "I am invincible!!!"' SIGTERM
i=1
while [ $i ]
do
	echo "To infinity and beyond"
	sleep 2
	((i++))
done
