#!/usr/bin/env bash
# configure localhost and facebook.com ips
# docker problem
cp /etc/hosts ~/hosts.new
sed -i 's/^.*localhost$/127.0.0.2 localhost/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
